class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'settings_title': 'Cài đặt',
      'appearance_section': 'GIAO DIỆN',
      'dark_mode': 'Chế độ tối (Dark Mode)',
      'dark_mode_subtitle': 'Sử dụng giao diện tối để bảo vệ mắt',
      'display_font': 'Font chữ hiển thị',
      'display_font_subtitle': 'Tùy chỉnh font chữ cho phần đọc',
      'language': 'Ngôn ngữ / Language',
      'language_subtitle': 'Chọn ngôn ngữ hiển thị',
      'ai_config_section': 'CẤU HÌNH AI',
      'translation_model': 'Mô hình dịch thuật',
      'translation_model_subtitle': 'Chọn mô hình ngôn ngữ chính',
      'manage_models': 'Quản lý Model đã tải',
      'manage_models_subtitle': 'model đã cài đặt',
      'translation_config_section': 'CẤU HÌNH DỊCH THUẬT',
      'project_folder': 'Thư mục dự án',
      'not_configured': 'Chưa cấu hình',
      'footer_credit': 'FluxOrigin v1.0.0 - Made with ☕ by d-init-d',
      'download_success': 'Tải model thành công!',
      'download_fail': 'Tải model thất bại.',
      'delete_model_confirm': 'Xác nhận xóa',
      'delete_model_question': 'Bạn có chắc muốn xóa model',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'deleted_model': 'Đã xóa model',
      'delete_fail': 'Xóa model thất bại',
      'manage_models_title': 'Quản lý Model đã tải',
      'no_models_installed': 'Chưa có model nào được tải',
      'delete_model_tooltip': 'Xóa model',
      'close': 'Đóng',
      // Sidebar
      'sidebar_translate': 'Dịch thuật',
      'sidebar_history': 'Lịch sử',
      'sidebar_dictionary': 'Từ điển',
      'sidebar_settings': 'Cài đặt',
      // Translate Screen
      'enter_text_placeholder': 'Nhập văn bản cần dịch...',
      'translate_now': 'Dịch ngay',
      'translating': 'Đang dịch...',
      'start_translation': 'BẮT ĐẦU DỊCH',
      'continue_translation': 'TIẾP TỤC DỊCH',
      'pause': 'Tạm dừng',
      'cancel_action': 'Hủy bỏ',
      'save_result': 'LƯU KẾT QUẢ',
      'translate_another': 'Dịch file khác',
      'local_dictionary': 'Từ điển cục bộ',
      'processing': 'Đang xử lý...',
      'translation_success': 'Dịch thành công!',
      'error_prefix': 'Lỗi: ',
      'please_configure_project': 'Vui lòng cấu hình thư mục dự án trước!',
      'file_saved_at': 'Đã lưu file tại: ',
      'error_saving_file': 'Lỗi khi lưu file: ',
      'save_result_dialog_title': 'Lưu kết quả dịch',
      'progress': 'Tiến độ: ',
      'delete_progress_tooltip': 'Xóa tiến độ và bắt đầu lại',
      'restart_from_beginning': 'Bắt đầu lại từ đầu',
      'pausing': 'Đang tạm dừng sau đoạn hiện tại...',
      'resuming': 'Đang tiếp tục dịch...',
      'initializing': 'Đang khởi tạo...',
      // History Screen
      'history_title': 'Lịch sử dịch thuật',
      'refresh_tooltip': 'Làm mới',
      'no_history': 'Chưa có lịch sử dịch',
      'no_history_subtitle': 'Các file đã dịch thành công sẽ hiển thị ở đây',
      'yesterday': 'Hôm qua',
      'days_ago': 'ngày trước',
      // Dictionary Screen
      'dictionary_title': 'Từ điển & Thuật ngữ',
      'dictionary_subtitle': 'Quản lý các tệp từ điển cá nhân và chuyên ngành.',
      'add_new': 'Thêm mới',
      'dictionary_name': 'TÊN TỪ ĐIỂN',
      'dictionary_size': 'KÍCH THƯỚC',
      'dictionary_entries': 'SỐ TỪ',
      'showing_dictionaries': 'Hiển thị dictionaries từ điển',
      'no_dictionaries': 'Chưa có từ điển nào',
      'no_dictionaries_subtitle': 'Thêm file .csv vào thư mục dictionary',
      // Upload Dictionary Modal
      'add_dict_title': 'Thêm từ điển mới',
      'dict_name_label': 'Tên hiển thị',
      'dict_name_hint': 'Nhập tên từ điển...',
      'dict_file_label': 'File dữ liệu (.json, .csv)',
      'select_file_btn': 'Chọn file',
      'file_selected': 'Đã chọn file:',
      'upload_btn': 'Thêm từ điển',
      'error_missing_info': 'Vui lòng nhập tên và chọn file',
      'drag_drop_or': 'Kéo và thả file hoặc',
      'browse_files': 'Chọn từ máy',
      'supported_dict_formats': 'Hỗ trợ .csv',
      // Common
      'confirm': 'Xác nhận',
      'success': 'Thành công',
      'failed': 'Thất bại',
      'save': 'Lưu',
      'source_text_hint': 'Nhập văn bản cần dịch...',
      'translate_button': 'Dịch',
      'auto_detect': 'Phát hiện ngôn ngữ',
      'copy': 'Sao chép',
      'clear': 'Xóa',
      'source_language': 'Ngôn ngữ nguồn',
      'target_language': 'Ngôn ngữ đích',
      'drag_drop_file': 'Kéo thả tài liệu vào đây',
      'supported_formats': 'Hỗ trợ .TXT, .EPUB',
      'unsupported_format_error': 'Chỉ hỗ trợ file .TXT và .EPUB',
      'drop_file_here': 'Thả file vào đây',
      'choose_file': 'Chọn file',
      'upload_dictionary_placeholder': 'Tải lên từ điển của bạn',
      'selected': 'Đã chọn',
      'change_file': 'Thay đổi',
      'local_mode_hint':
          'Nếu không tải lên từ điển, mặc định AI sẽ tự tạo mới từ điển cục bộ (không dùng Internet).',
      'ai_auto_mode': 'AI Tự động (Online)',
      'ai_auto_hint':
          'Hệ thống có quyền truy cập internet để hoàn thành từ điển.',
      'error_picking_file': 'Lỗi chọn file: ',
      'lang_en': 'Tiếng Anh',
      'lang_vi': 'Tiếng Việt',
      'lang_cn': 'Tiếng Trung',
      'default_label': 'Mặc định',
    },
    'en': {
      'settings_title': 'Settings',
      'appearance_section': 'APPEARANCE',
      'dark_mode': 'Dark Mode',
      'dark_mode_subtitle': 'Use dark theme to reduce eye strain',
      'display_font': 'Display Font',
      'display_font_subtitle': 'Customize font for reading',
      'language': 'Language / Ngôn ngữ',
      'language_subtitle': 'Choose display language',
      'ai_config_section': 'AI CONFIGURATION',
      'translation_model': 'Translation Model',
      'translation_model_subtitle': 'Select primary language model',
      'manage_models': 'Manage Downloaded Models',
      'manage_models_subtitle': 'models installed',
      'translation_config_section': 'TRANSLATION CONFIG',
      'project_folder': 'Project Folder',
      'not_configured': 'Not configured',
      'footer_credit': 'FluxOrigin v1.0.0 - Made with ☕ by d-init-d',
      'download_success': 'Model downloaded successfully!',
      'download_fail': 'Model download failed.',
      'delete_model_confirm': 'Confirm Delete',
      'delete_model_question': 'Are you sure you want to delete model',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted_model': 'Model deleted',
      'delete_fail': 'Failed to delete model',
      'manage_models_title': 'Manage Downloaded Models',
      'no_models_installed': 'No models installed',
      'delete_model_tooltip': 'Delete model',
      'close': 'Close',
      // Sidebar
      'sidebar_translate': 'Translate',
      'sidebar_history': 'History',
      'sidebar_dictionary': 'Dictionary',
      'sidebar_settings': 'Settings',
      // Translate Screen
      'enter_text_placeholder': 'Enter text to translate...',
      'translate_now': 'Translate Now',
      'translating': 'Translating...',
      'start_translation': 'START TRANSLATION',
      'continue_translation': 'CONTINUE TRANSLATION',
      'pause': 'Pause',
      'cancel_action': 'Cancel',
      'save_result': 'SAVE RESULT',
      'translate_another': 'Translate another file',
      'local_dictionary': 'Local Dictionary',
      'processing': 'Processing...',
      'translation_success': 'Translation Successful!',
      'error_prefix': 'Error: ',
      'please_configure_project': 'Please configure project folder first!',
      'file_saved_at': 'File saved at: ',
      'error_saving_file': 'Error saving file: ',
      'save_result_dialog_title': 'Save Translation Result',
      'progress': 'Progress: ',
      'delete_progress_tooltip': 'Delete progress and restart',
      'restart_from_beginning': 'Restart from beginning',
      'pausing': 'Pausing after current segment...',
      'resuming': 'Resuming translation...',
      'initializing': 'Initializing...',
      // History Screen
      'history_title': 'Translation History',
      'refresh_tooltip': 'Refresh',
      'no_history': 'No translation history',
      'no_history_subtitle': 'Successfully translated files will appear here',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      // Dictionary Screen
      'dictionary_title': 'Dictionaries & Terms',
      'dictionary_subtitle':
          'Manage personal and specialized dictionary files.',
      'add_new': 'Add New',
      'dictionary_name': 'DICTIONARY NAME',
      'dictionary_size': 'SIZE',
      'dictionary_entries': 'ENTRIES',
      'showing_dictionaries': 'Showing dictionaries',
      'no_dictionaries': 'No dictionaries found',
      'no_dictionaries_subtitle': 'Add .csv files to the dictionary folder',
      // Upload Dictionary Modal
      'add_dict_title': 'Add New Dictionary',
      'dict_name_label': 'Display Name',
      'dict_name_hint': 'Enter dictionary name...',
      'dict_file_label': 'Data File (.json, .csv)',
      'select_file_btn': 'Select File',
      'file_selected': 'File selected:',
      'upload_btn': 'Add Dictionary',
      'error_missing_info': 'Please enter name and select file',
      'drag_drop_or': 'Drag and drop file or',
      'browse_files': 'Browse',
      'supported_dict_formats': 'Supports .csv',
      // Common
      'confirm': 'Confirm',
      'success': 'Success',
      'failed': 'Failed',
      'save': 'Save',
      'source_text_hint': 'Enter text to translate...',
      'translate_button': 'Translate',
      'auto_detect': 'Auto Detect',
      'copy': 'Copy',
      'clear': 'Clear',
      'source_language': 'Source Language',
      'target_language': 'Target Language',
      'drag_drop_file': 'Drag and drop file here',
      'supported_formats': 'Supports .TXT, .EPUB',
      'unsupported_format_error': 'Only .TXT and .EPUB files are supported',
      'drop_file_here': 'Drop file here',
      'choose_file': 'Choose File',
      'upload_dictionary_placeholder': 'Upload your dictionary',
      'selected': 'Selected',
      'change_file': 'Change',
      'local_mode_hint':
          'If no dictionary is uploaded, AI will create a local one by default (offline).',
      'ai_auto_mode': 'AI Auto (Online)',
      'ai_auto_hint': 'System has internet access to complete the dictionary.',
      'error_picking_file': 'Error picking file: ',
      'lang_en': 'English',
      'lang_vi': 'Vietnamese',
      'lang_cn': 'Chinese',
      'default_label': 'Default',
    },
  };

  static String get(String lang, String key) {
    return _localizedValues[lang]?[key] ?? _localizedValues['vi']![key]!;
  }
}
